name: io.elementary.settings-daemon
buildsystem: meson
dependencies:
  - libaccountsservice-dev
  - libdbus-1-dev
  - libgeoclue-2-dev
  - libgranite-dev
  - meson
  - valac
sources:
  - type: git
    url: https://github.com/elementary/settings-daemon
    tag: 1.2.0
