name: elementary/applications-menu
buildsystem: meson
dependencies:
  - bc
  - libgee-0.8-dev
  - libgranite-dev
  - libgtk-3-dev
  - libhandy-1-dev
  - libjson-glib-dev
  - libplank-dev
  - libsoup2.4-dev
  - libswitchboard-2.0-dev
  - libwingpanel-dev
  - libzeitgeist-2.0-dev
  - meson
  - pkg-config
  - valac
sources:
  - type: git
    url: https://github.com/elementary/applications-menu
    tag: master
