name: elementary/default-settings
buildsystem: meson
dependencies:
  - libaccountsservice-dev
  - libdbus-1-dev
  - libglib2.0-bin
  - libpolkit-gobject-1-dev
  - meson
  - python3
sources:
  - type: git
    url: https://github.com/elementary/default-settings
    tag: main
