name: elementary/session-settings
buildsystem: meson
build-options:
  wayland: true
dependencies:
  - desktop-file-utils
  - gettext
  - gnome-keyring
  - gnome-settings-daemon
  - gnome-settings-daemon-dev
  - meson
  - orca
sources:
  - type: git
    url: https://github.com/elementary/session-settings
    tag: remove-onboard
