name: elementary/settings
buildsystem: meson
dependencies:
  - gettext
  - libgee-0.8-dev
  - libglib2.0-dev
  - libgranite-7-dev
  - libgtk-4-dev
  - libadwaita-1-dev
  - meson
  - valac
sources:
  - type: git
    url: https://github.com/elementary/switchboard
    tag: main
