name: elementary/settings-daemon
buildsystem: meson
dependencies:
  - desktop-file-utils
  - libaccountsservice-dev
  - libdbus-1-dev
  - libfwupd-dev
  - libgeoclue-2-dev
  - libgranite-dev
  - meson
  - valac
sources:
  - type: git
    url: https://github.com/elementary/settings-daemon
    tag: main
