name: io.elementary.switchboard.applications
buildsystem: meson
dependencies:
  - gettext
  - libflatpak-dev
  - libgranite-dev
  - libgtk-3-dev
  - libswitchboard-2.0-dev
  - meson
  - valac
sources:
  - type: git
    url: https://github.com/elementary/switchboard-plug-applications
    tag: 6.0.1
