name: io.elementary.wingpanel.bluetooth

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
      - name: Pull changes ⬇️
        uses: actions/checkout@v3

      - name: Install dependencies ⬇️
        run: |
          apt-get update
          apt-get install -y git python3-yaml

      - name: Build io.elementary.wingpanel.bluetooth 🔨
        run: |
          ./builder \
            --distro ubuntu:22.04 \
            --package io.elementary.wingpanel.bluetooth